### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by kshashov** [OlegNyr/java-telegram-bot-mvc#4]
Я бы хотел использовать код в своем репозитории, но формально этого делать не имею права, из-за отсутствия в проекте лицензии. 
Можете выбрать лицензию и добавить файл? MIT если не жалко :) 

[Licensing a repository](https://help.github.com/en/articles/licensing-a-repository)
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by OlegNyr** [comment]
Сегодня добавлю

**Comment by OlegNyr** [comment]
сменил лицензию
